version: '3.8'
services:
    rasa:
      image: rasa/rasa:3.0
      container_name: chatbot_rasa-rasa-1
      volumes:
        - ./:/app/
      ports:
        - 5005:5005
      command: 
        - run
        - --cors
        - "*"
        - --enable-api
        - --debug
        - --endpoints
        - endpoints.yml
    action_server:
      container_name: chatbot_rasa-action_server-1
      build: .
      ports: 
        - "5055:5055"

    postgres:
      image: postgres:latest
      container_name: chatbot_rasa-postgres-1
      restart: always
      environment:
        - POSTGRES_USER=project_admin
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=rasa
      volumes:
        - ./scripts:/scripts/
      ports: 
        - "5431:5431"
    
  #  pgAdmin:
  #    image: dpage/pgadmin4
  #    restart: always
  #    environment:
  #      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
   #     - PGADMIN_DEFAULT_PASSWORD=root
   #   ports:
   #     - "5050:80"

   # nodejs:
   #   image: node:17-alpine3.12
   #   volumes:
   #     - ./:/Node-Backend
